# Generated by Django 4.2.8 on 2024-01-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trainlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisenote",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="trainlog.exercise",
                unique_for_date="date",
            ),
        ),
    ]
