# Generated by Django 4.2.8 on 2024-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainlog", "0004_alter_exercisenote_exercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="muscle_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Chest", "Chest"),
                    ("Shoulders", "Shoulders"),
                    ("Triceps", "Triceps"),
                    ("Back", "Back"),
                    ("Biceps", "Biceps"),
                    ("Arms", "Arms"),
                    ("Quadriceps", "Quadriceps"),
                    ("Hamstrings", "Hamstrings"),
                    ("Hip", "Hip"),
                    ("Calves", "Calves"),
                    ("Abs", "Abs"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
