# Generated by Django 4.2 on 2023-04-14 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trainlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercisenote",
            options={"ordering": ["note"]},
        ),
    ]
