# Generated by Django 4.2 on 2023-04-14 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trainlog", "0002_alter_exercisenote_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="sub_muscles",
            field=models.ManyToManyField(blank=True, to="trainlog.submusclegroup"),
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="muscle",
        ),
        migrations.AddField(
            model_name="exercise",
            name="muscle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="muscle_group",
                to="trainlog.musclegroup",
            ),
        ),
    ]
