# Generated by Django 4.2 on 2023-04-15 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trainlog", "0003_exercise_sub_muscles_remove_exercise_muscle_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="musclegroup",
            table="muscle_group",
        ),
    ]
